[package]
name = "kikiutils"
version = "0.5.1"
edition = "2021"

authors = ["kiki-kanri"]
categories = []
description = "A utility library to simplify Rust development."
exclude = [
    ".gitignore",
    ".vscode/",
    "Makefile.toml",
    "modify-files-permissions.sh",
    "package.json",
    "release.sh",
]

keywords = ["utils"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/kikiutils/rust"

# Dependencies
[dependencies]
anyhow = { version = "1.0.100", optional = true }
dashmap = { version = "6.1.0", optional = true }
futures = { version = "0.3.31", optional = true }
time = { version = "0.3.44", features = ["formatting", "local-offset", "macros"], optional = true }
tokio = { version = "1.47.1", features = ["macros", "rt", "signal", "sync"], optional = true }
tokio-util = { version = "0.7.16", optional = true}
tracing-subscriber = { version = "0.3.20", features = ["time"], optional = true }

[dev-dependencies]
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["full"] }

# Features
[features]
default = []

anyhow-ext = ["anyhow"]
signal = ["anyhow", "tokio"]
task = ["anyhow", "dashmap", "futures", "tokio", "tokio-util"]
tracing = ["anyhow", "time", "tracing-subscriber"]

all = ["anyhow-ext", "signal", "task", "tracing"]
full = ["all"]
